### ISSUE TITLE
customise KBarSearch 

### ISSUE THREAD

**Issue by devenbhooshan** [timc1/kbar#157]
hi @timc1 

is it possible to customise the whole search bar currently? It looks like I can pass classnames(to customize the style) to the KBarSearch but I cannot customise it fully(like adding an icon in the search bar or customise placeholder contextually based on the currentRootActionId) 

thanks for building this library.

**Comment by timc1** [comment]
Hey @devenbhooshan! You can build your own search component and leverage the APIs provided by `kbar` in order to build the experience you'd like. Take a look at the [implementation within `KBarSearch`](https://github.com/timc1/kbar/blob/main/src/KBarSearch.tsx) and you'll see that it is itself built on top of the `useKBar` hook
