### ISSUE TITLE
Special keys in shortcuts

### ISSUE THREAD

**Issue by SpaceHolderdJs** [timc1/kbar#174]
Hi!
How should I use special keys in action`s shortcuts? (arrows, cntr, ect)

**Comment by ihassansattar** [comment]
+1, I cannot figure out how to use arrow keys as hotkeys.
Would have been better if added somewhere in the docs.

**Comment by CarlosNZ** [comment]
Yeah same! [This doc](https://kbar.vercel.app/docs/concepts/shortcuts) says that over-riding the default "Cmd-K" key can be done using [TinyKeys syntax](https://jamiebuilds.github.io/tinykeys/), but this doesn't seem to work for regular Action shortcuts.

Would really like to create shortcuts for Enter, Up & Down arrow, and Escape and was hoping to be able to use Kbar rather than adding another package into the mix.

**Comment by timc1** [comment]
How do you imagine using arrow up/down/enter as part of your shortcuts? Would they be paired with another key ie meta/ctrl?

**Comment by SpaceHolderdJs** [comment]
Hi, probably yes, or even use it separately as posibility to navigate
between application parts

вс, 20 мар. 2022 г., 16:44 Tim ***@***.***>:
