### ISSUE TITLE
Priority enhancements

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#194]
Collecting feedback for fine tuning priority #190.

- Simplify the API such that users do not have to remember to set a priority on a section on the very first section of that name
- How can developers easily update priority for an action or section without needing to reregister?

**Comment by a-churchill** [comment]
@timc1 Let me know if you want me to open a separate issue or even try a PR for this, but it would be great if section order could be deprioritized when searching. It leads to strange results - see this example from our current implementation:
<img width="627" alt="image (37)" src="https://user-images.githubusercontent.com/18105223/165602443-e94ec654-f63e-4f6d-a940-cd83542dc837.png">

I'm thinking section ordering should only be used as a tiebreaker between otherwise equally scored results?
