### ISSUE TITLE
Unclear that this is a React component

### ISSUE THREAD

**Issue by dz4k** [timc1/kbar#28]
Just a little heads-up: The landing page at https://kbar.vercel.app/ doesn't actually contain the word "React" anywhere,  this confused me a little when I saw the sample code with JSX syntax.

**Comment by goodevilgenius** [comment]
Same confusion here. I saw this on CSS Tricks, which didn't mention this was for React. I followed the link to the homepage, which doesn't say it. I also didn't see a link to the GitHub repo, so I had to Google it to find this repo, which also doesn't mention React in the README.

So, I'm thinking that the examples are just one way of using it, since it doesn't mention React. Only when I looked at package.json and saw React required that I was sure this was definitely a React component.

Pretty disappointed since I mainly work in Vue or vanilla JS. TuS looks very cool.

**Comment by timc1** [comment]
Thanks for the feedback! The Readme is updated to reflect that. Fun fact, we can actually strip the React part out of this library and create a framework agnostic implementation – something for the future :-)

**Comment by mike-luabase** [comment]
@timc1 any timeline on that? Would love to use this in a vue app

**Comment by timc1** [comment]
Hey @mike-luabase! No specific timeline for a Vue port; however, there looks to be some implementations out in the wild as you mentioned, https://github.com/bytebase/vue-kbar.

**Comment by mike-luabase** [comment]
@timc1 thanks Tim!
