### ISSUE TITLE
Display subtitle along with name for actions

### ISSUE THREAD

**Issue by austincondiff** [timc1/kbar#31]
Kbar should allow developers the option to provide more context to users by displaying a subtitle along with the name. In my specific use-case I'd like to expose my complex navigation to kbar. Because things are nested, it may be helpful to users to see a navigation path under the name. 

This would look something like this.
> **Gizmo**
> _Products `▶` Electronics_

To display the subtitle as shown above, we may do something like this in our actions array.
```js
const actions = [
  ...
  {
    name: "Gizmo", 
    subtitle: "Products ▶ Electronics", 
    perform: () => window.location.pathname = "/products/electronics/gizmo" 
  },
  ...
];
```

If the search string contained words in `subtitle`, kbar would return that given item.

**Comment by timc1** [comment]
Hey @austincondiff, it'd be best to keep `Action` as simple as possible – I'd imagine there are going to be many requests for adding additional properties to actions, so we'll need to think about a generic solution to handle these requests.

Since you can have control over the rendering of each result, a nice workaround for now which will support search by default, is to give your action a name like `"Gizmo [Products ▶ Electronics]"`. When you render the result, you can strip out the content within the brackets and render the string as the subtitle.

**Comment by austincondiff** [comment]
@timc1 Thanks for the workaround, but this seems somewhat counter-intuitive. At a very bare-minimum I'd expect to be able to pass name some jsx. Would that be possible? (Although, if we did that I assume it wouldn't be searchable) 🤔

It looks like even spotlight has secondary text...
![image](https://user-images.githubusercontent.com/806104/133692467-5e936369-3eaa-4f56-845c-b93be1230d4a.png)

Could this justify doing the same in kbar?

**Comment by timc1** [comment]
Alright, I gave it some time to sink in and think this is valid to move forward with. Thanks for the suggestion @austincondiff :-)
