### ISSUE TITLE
unable to input Chinese correctly

### ISSUE THREAD

**Issue by halleystar** [timc1/kbar#327]
there is a bug in kbar. I only wanted to input the Chinese characters '你好'. but kbar also included the Pinyin input I used to spell '你好'. The correct look should only contain "你好" and not contain any characters in front of "你好"
![image](https://github.com/timc1/kbar/assets/5334156/99315640-0eb2-4233-a408-5301573fd970)

**Comment by timc1** [comment]
What version of `kbar` are you using?

https://github.com/timc1/kbar/assets/12195101/5fdb6538-bf33-4859-9b79-874d7ae68d5d

**Comment by halleystar** [comment]
Hey all! This is the version i reference: "kbar": "^0.1.0-beta.41". But the issue still exists
![动画](https://github.com/timc1/kbar/assets/5334156/4728da89-2f55-45ba-a488-593c3549b7a9)

**Comment by windily-cloud** [comment]
I have same issue, 0.1.0-beta-42, this is sandbox demo:

https://codesandbox.io/s/kbar-test-fx6894?file=/src/index.js


https://github.com/timc1/kbar/assets/30640638/1cac5aa3-469e-4332-b5d3-54c9f844194e

Thx for any reply.

**Comment by thekoc** [comment]
Some problem here

**Comment by life-plant** [comment]
I found the same problem, and then I found that using ReactDOM.createRoot(document.getElementById("root")!).render(xxx) to create a react project in a react 18 project will cause KBarSearch fail to input Chinese, but there is no problem with using ReactDOM.render(xxx). react 17 is also no problem, because it is also created project with ReactDOM.render(xxx).

**Comment by donghoon-lee-mrt** [comment]
Same issue when I try to input Korean.

**Comment by liruifengv** [comment]
+1
